<?php
$imBPwd = "admin";
$imBEmail = "bebooks_comentarios@yahoo.com";
$imBServerRoot = "http://www.bebooks.es/";
$imDir = "../.";
$imFilesPrefix = "x5_149963_";
$imBCommentsApproved = 0;
$imBLang = Array("Publicado por","en","Todos leídos","comentarios","comentarios","No comentarios","Nombre","E-mail","Internet website","Mensaje","Enviar","Administración Blog","Visualizar","Eliminar","¿Eliminar este comentario?","Contraseña:","Acceder","Regresar al Blog","Aprobar","¿Aprobar este comentario?","Desaprobar","¿Desaprobar este comentario y esconderlo?","¡Comentario enviado! El comentario será visible después de la aprobación del administrador del sitio.","No ha sido posible insertar el comentario.","Blog: Nuevo comentario.","Se ha insertado un Nuevo comentario al blog en el artículo","Imposible acceder a la carpeta de los comentarios","Valor ausente para el campo","Usar el siguiente enlace para aprobar el comentario","Usar el siguiente enlace para desaprobar el comentario","Esta característica es válida solamente después de haber publicado el sitio en Internet.");
$imBAddThis = "<script type=\"text/javascript\">addthis_pub = '';</script><a href=\"http://www.addthis.com/bookmark.php\" onmouseover=\"return addthis_open(this, '', '[URL]', '[TITLE]')\" onmouseout=\"addthis_close()\" onclick=\"return addthis_sendto()\"><img src=\"http://s7.addthis.com/button1-share.gif\" width=\"125\" height=\"16\" border=\"0\" alt=\"\" /></a><script type=\"text/javascript\" src=\"http://s7.addthis.com/js/152/addthis_widget.js\"></script>";
$imBCatName = Array("Curiosidades","Eventos");
$post['title'] = "Taller para Escritores Novatos";
$post['author'] = "Dani";
$post['category'] = 1;
$post['summary'] = "A correr que se acaban las plazas!!!!";
$post['body'] = "<strong>Sed sapien dolor</strong>, pretium vitae adipiscing sit amet, adipiscing in risus. Nulla convallis, ligula eu pretium porttitor, mauris mauris commodo odio, eu mollis lacus purus at sapien. Vivamus accumsan mattis lectus, in ultrices nisi porttitor et. Proin dapibus lacinia nisl, non sodales lacus pretium id. Quisque eu dui dui, vitae aliquam tellus. Fusce vel tortor leo, a hendrerit nibh. Sed sed lectus ut nisl feugiat mollis. Mauris auctor lobortis varius. Etiam lacinia malesuada purus eget tristique. Donec sed lectus metus, vel condimentum neque. <div class=\"ImBlogQuote\">Class aptent taciti</div> sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis at risus mauris. Nulla ipsum mauris, aliquam at commodo sed, malesuada ac tortor. Phasellus tempus aliquet adipiscing. Mauris semper suscipit hendrerit. Integer massa ipsum, tincidunt a lobortis eu, tempus non leo. Curabitur mollis venenatis blandit. Nulla facilisi.<br /><br /><strong>Nulla ipsum elit</strong>, bibendum eget euismod ut, semper eget dui. Vestibulum faucibus feugiat orci, id varius quam tincidunt sed. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean nibh leo, sodales eu pellentesque vitae, rhoncus ac tellus. Nullam et ornare ligula. Sed nisi augue, condimentum cursus cursus ut, euismod sed odio. Quisque sollicitudin mollis enim, eu blandit libero tristique a. Suspendisse consequat tincidunt lectus, mattis sodales sapien viverra et. Duis luctus dolor quis metus ornare aliquet. Aliquam lacinia vulputate felis, a luctus erat viverra nec. Nullam at diam vel magna tempor cursus. Etiam lobortis dui sed felis hendrerit ut rhoncus orci volutpat. Vivamus ut tempor eros. Suspendisse a urna sed eros hendrerit venenatis. Pellentesque sit amet scelerisque diam. Nunc at aliquet ante. In fermentum odio non ipsum adipiscing viverra. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus<br />";
$post['timestamp'] = "22/07/2009 21:42:00";
$post['foo_html'] = "";
$post['comments'] = 0;
$imBPosts['hc5'] = $post;
$imBCat[1][] = 'hc5';
$imBMonths['200907'][] = 'hc5';
$post['title'] = "Maquinas Antiguas de Escribir";
$post['author'] = "Rosa";
$post['category'] = 0;
$post['summary'] = "Recordando el Pasado";
$post['body'] = "<img src=\"ebooks.jpg\" /><br /><br /><strong>Lorem ipsum </strong>dolor sit amet, consectetur adipiscing elit. Integer porttitor egestas tincidunt. Nulla accumsan facilisis erat sed porttitor. Quisque rutrum lacus eu leo semper suscipit pharetra urna blandit. Etiam ut quam eros, in mollis nisi. Nam sed magna vitae dolor laoreet consequat vel dictum diam. Maecenas vitae nisl nulla. Mauris eleifend placerat nisl ac ultrices. Quisque laoreet semper est nec scelerisque. Duis cursus porttitor ipsum quis interdum. Etiam a nulla eu quam posuere lacinia. Nulla luctus condimentum ligula, a eleifend lorem dictum sed. Donec nulla velit, euismod eu accumsan sit amet, aliquam id nibh. Aliquam a consectetur elit. In congue, felis sed vestibulum fermentum, sem neque aliquet nulla, fringilla tristique ante lacus vel turpis.<br /><br /><strong>Donec quis viverra nibh</strong>. Cras eget venenatis mauris. Nullam blandit pretium tortor id semper. Vestibulum lacinia lectus vitae dolor tempus eu tempus erat euismod. Sed aliquet metus at justo pellentesque imperdiet. Fusce velit enim, pretium id luctus vitae, semper in arcu. Suspendisse potenti. Mauris est augue, dictum id tristique non, volutpat in lectus. Duis metus felis, ultrices in fringilla id, consectetur nec nulla. Nulla porttitor malesuada mi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus egestas consectetur odio, sit amet euismod mi porta ac. Morbi risus odio, gravida non pretium ut, porta in ipsum. Ut velit metus, tincidunt quis sagittis nec, consectetur quis ante. Fusce facilisis rhoncus metus, tempor posuere felis fermentum suscipit. Integer tincidunt faucibus lorem id accumsan. Fusce consequat fermentum neque posuere lacinia. Etiam ornare mattis diam, at consequat lacus pharetra vitae. Aliquam et nisl diam, in dignissim turpis. Morbi vulputate metus in quam mattis mattis. <br />";
$post['timestamp'] = "11/07/2009 20:01:08";
$post['foo_html'] = "";
$post['comments'] = 0;
$imBPosts['cc0'] = $post;
$imBCat[0][] = 'cc0';
$imBMonths['200907'][] = 'cc0';
?>
